name = "Ion"
uuid = "8ffca487-8d2f-5690-aa24-45fb2f06359c"
authors = ["vdayanand <venkatesh@juliacomputing.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
